name = "tanzhen"
main = "src/index.js"
compatibility_date = "2026-06-05"

# 告诉 Cloudflare 该项目需要一个 D1 数据库，绑定名称必须是 DB
[[d1_databases]]
binding = "DB"
database_name = "monitor_db" 
database_id = "bd9841b1-35fd-46a2-ba8b-c27d89d7d68a" # 👈 填入真正的 ID！
